import { Inter } from "next/font/google";
import "../styles/globals.css";
import UIprovider from "./ui-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UIprovider>
          {children}
        </UIprovider>
      </body>
    </html>
  );
}
